{% set name = "compas_convert" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 913d5e65057d097fff0101b11b8961152292c52a03bdaea479d3ed48432871ef

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
    - wheel
  run:
    - compas >=0.17.2,<1.11
    - python >={{ python_min }}

test:
  source_files:
    - tests
    - conftest.py
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest -vv tests

about:
  home: https://github.com/biodigitalmatter/compas_convert
  summary: Conversions between compas objects and CAD specific objects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tetov
